---@type LazySpec
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    colorscheme = require("env").colorscheme,
    highlights = {
      init = {
        StatusLine = { link = "Normal" },
        FloatBorder = { link = "Question" },
        NormalFloat = { link = "Normal" },

        WhichKeyFloat = { link = "Normal" },

        NeoTreeNormal = { link = "Normal" },
        NeoTreeNormalNC = { link = "Normal" },
      },
    },
    icons = {
      LSPLoading1 = "⠋",
      LSPLoading2 = "⠙",
      LSPLoading3 = "⠹",
      LSPLoading4 = "⠸",
      LSPLoading5 = "⠼",
      LSPLoading6 = "⠴",
      LSPLoading7 = "⠦",
      LSPLoading8 = "⠧",
      LSPLoading9 = "⠇",
      LSPLoading10 = "⠏",
      ActiveLSP = "󰓅",
      ActiveTS = "",
      ArrowLeft = "",
      ArrowRight = "",
      BufferClose = "",
      DapBreakpoint = "",
      DapBreakpointCondition = "",
      DapBreakpointRejected = "",
      DapLogPoint = ".>",
      DapStopped = "󰁕",
      DefaultFile = "󰈙",
      Diagnostic = "󰒡",
      DiagnosticHint = "",
      DiagnosticError = "",
      DiagnosticInfo = "",
      DiagnosticWarn = "",
      Ellipsis = "…",
      FileModified = "",
      FileReadOnly = "",
      FoldClosed = "",
      FoldOpened = "",
      FoldSeparator = " ",
      FolderClosed = "󰉋",
      FolderEmpty = "󱞞",
      FolderOpen = "󰉖",
      Git = "󰊢",
      GitAdd = "",
      GitChange = "",
      GitDelete = "",
      GitBranch = "󰘬",
      GitConflict = "󰘭",
      GitRenamed = "󰪹",
      GitStaged = "󰌕",
      GitUnstaged = "󰫋",
      GitIgnored = "󰈉",
      GitUntracked = "󱈶",
      LSPLoaded = "",
      MacroRecording = "",
      Paste = "󰅌",
      Search = "",
      Selected = "❯",
      Spellcheck = "󰓆",
      TabClose = "󰅙",
    },
  },
}
